### ISSUE TITLE
Configurar extensões com o Slack

### ISSUE THREAD

**Issue by miguelpimentel** [fga-gpp-mds/2018.1-Grupo4#16]
**Descrição**

Configurar plugins de ferramentas tais como Github e Slack ao Slack

**Responsável**

Miguel Pimentel

**Horário: 17 e 30**
**Data: 10/03/2018**

**Comment by luis-gustavo** [comment]
@miguelpimentel O que está faltando para fechar essa issue ?

**Comment by miguelpimentel** [comment]
Nada, arrumei agora com o Taiga, na próximo encontro com o time vou mostrar como usar as tags juntos com o git
